Create:
    path: /usercreate
    controller: App\Controller\CreateAccountController::index
login:
    path: /login
    controller: App\Controller\UserController::signin
homepage:
    path: /home
    controller: App\Controller\HomeController::index
SendEMail:
     path: /send-email
     controller: App\Controller\UserController::sendEmail
ValLogin:
    path: /user
    controller: App\Controller\UserController::signin